// Hizmet (Offer) kataloğu — 3 kategori altında.
// Fiyatlar TL cinsinden. Sektör hedeflemesi sectorPriority.ts ile uyumlu id'ler kullanır.

import { Offer } from './types'

export const OFFERS: Offer[] = [
  {
    id: 'ai_lead_response',
    name: 'AI Lead Response Agent',
    category: 'revenue',
    description: 'Reklam/form/WhatsApp lead\'lerine 5 dakika içinde otomatik dönüş.',
    targetSectors: ['health_clinic', 'real_estate', 'automotive', 'education', 'insurance'],
    problemSolved: '5 dakikadan geç dönüş alan lead rakibe kayar.',
    setupPrice: 8000,
    monthlyPrice: 15000,
    deliveryDays: 7,
    difficulty: 'medium',
    salesPromise: 'Her lead\'e 5 dakikada dönüş, kaçan satışı sıfırla.',
    antiPatterns: ['"AI bot satıyoruz" diye başlama', 'Teknik özelliklerle değil, kaçan parayla satılır'],
    checklist: [
      'Mevcut lead kanalları haritalandı',
      'Yanıt şablonları sektör diline göre yazıldı',
      'WhatsApp/form entegrasyonu yapıldı',
      'İlk hafta sonrası performans raporu hazırlandı',
    ],
    upsells: ['followup_agent', 'appointment_recovery', 'review_engine'],
  },
  {
    id: 'old_customer_reactivation',
    name: 'Eski Müşteri / Eski Hasta Canlandırma',
    category: 'revenue',
    description: 'Geçmiş müşteri listelerine segment bazlı kampanya.',
    targetSectors: ['health_clinic', 'automotive', 'insurance', 'ecommerce'],
    problemSolved: 'Eski müşteri listesi ölü duruyor — yeniden gelir üretmiyor.',
    setupPrice: 10000,
    monthlyPrice: 12000,
    deliveryDays: 10,
    difficulty: 'medium',
    salesPromise: 'Listenizdeki ölü müşteriler 30 günde geri gelir.',
    antiPatterns: ['Yeni müşteri kazanma odaklı sektörlerde ön plana koymama'],
    checklist: ['Liste temizleme + segmentasyon', 'Mesaj akışı', 'İlk kampanya', 'Dönüş raporu'],
    upsells: ['crm_reactivation', 'review_engine'],
  },
  {
    id: 'old_patient_reactivation',
    name: 'Eski Hasta Canlandırma (Klinik)',
    category: 'revenue',
    description: 'Diş, estetik, klinikler için eski hastaya kontrol/check-up daveti.',
    targetSectors: ['health_clinic'],
    problemSolved: 'Düzenli kontrol gerektiren hastalar takip edilmiyor.',
    setupPrice: 10000,
    monthlyPrice: 12000,
    deliveryDays: 10,
    difficulty: 'medium',
    salesPromise: '6 ayı geçmiş hastalara akıllı davet, randevu üretimi.',
    antiPatterns: [],
    checklist: ['Hasta listesi segmenti', 'Davet mesajı', 'Randevu yönlendirme'],
    upsells: ['review_engine', 'appointment_recovery'],
  },
  {
    id: 'followup_agent',
    name: 'Follow-up Agent',
    category: 'revenue',
    description: 'Lead aşamasında bekleyenlere otomatik takip dizisi.',
    targetSectors: ['health_clinic', 'real_estate', 'insurance', 'education', 'automotive'],
    problemSolved: 'İlk mesaja yanıt vermeyen lead\'ler unutuluyor.',
    setupPrice: 6000,
    monthlyPrice: 9000,
    deliveryDays: 5,
    difficulty: 'low',
    salesPromise: '3 aşamalı takip dizisi ile %30 daha fazla dönüş.',
    antiPatterns: [],
    checklist: ['Takip mesaj dizisi', 'Kanal seçimi (WA/SMS/email)', 'Performans ölçümü'],
    upsells: ['ai_lead_response', 'proposal_desk'],
  },
  {
    id: 'appointment_recovery',
    name: 'Randevu Kurtarma Sistemi',
    category: 'revenue',
    description: 'No-show önleme, hatırlatma, yeniden randevulandırma.',
    targetSectors: ['health_clinic', 'beauty', 'automotive'],
    problemSolved: 'Randevuya gelmeyen müşteri/hasta yüzünden zaman ve gelir kaybı.',
    setupPrice: 7000,
    monthlyPrice: 10000,
    deliveryDays: 7,
    difficulty: 'low',
    salesPromise: 'No-show oranınızı yarıya indirin.',
    antiPatterns: [],
    checklist: ['Hatırlatma akışı', 'No-show sonrası yeniden randevulandırma', 'Aylık rapor'],
    upsells: ['review_engine', 'followup_agent'],
  },
  {
    id: 'whatsapp_sales_assistant',
    name: 'WhatsApp Satış Asistanı',
    category: 'revenue',
    description: 'WhatsApp üzerinden ön satış, soru-cevap, randevu yönlendirme.',
    targetSectors: ['health_clinic', 'real_estate', 'automotive', 'ecommerce'],
    problemSolved: 'WhatsApp\'a düşen mesajlara saatler içinde dönüş yapılıyor.',
    setupPrice: 9000,
    monthlyPrice: 12000,
    deliveryDays: 10,
    difficulty: 'medium',
    salesPromise: '7/24 müşteri dönüşü, satışı kapatan asistan.',
    antiPatterns: [],
    checklist: ['Senaryo akışı', 'Sektör dili eğitimi', 'Devir hattı'],
    upsells: ['ai_lead_response', 'proposal_desk'],
  },
  {
    id: 'proposal_desk',
    name: 'Teklif Hazırlama & Takip Masası',
    category: 'revenue',
    description: 'Teklif şablonları, otomatik takip, e-imza akışı.',
    targetSectors: ['real_estate', 'logistics', 'insurance'],
    problemSolved: 'Teklifler manuel hazırlanıyor, gönderildikten sonra unutuluyor.',
    setupPrice: 8000,
    monthlyPrice: 9000,
    deliveryDays: 7,
    difficulty: 'low',
    salesPromise: 'Teklif çıkışı 10 dakikaya, takip otomatik.',
    antiPatterns: [],
    checklist: ['Şablonlar', 'Takip dizisi', 'Performans paneli'],
    upsells: ['followup_agent'],
  },
  {
    id: 'renewal_engine',
    name: 'Yenileme Motoru',
    category: 'revenue',
    description: 'Poliçe/abonelik yenileme otomasyonu, çapraz satış önerileri.',
    targetSectors: ['insurance'],
    problemSolved: 'Yenileme tarihi gelen poliçe unutuluyor — gelir kaybı.',
    setupPrice: 10000,
    monthlyPrice: 12000,
    deliveryDays: 14,
    difficulty: 'medium',
    salesPromise: 'Yenileme oranınızı %20-30 yükseltin.',
    antiPatterns: [],
    checklist: ['Yenileme listesi', 'Hatırlatma + çapraz satış akışı', 'Aylık rapor'],
    upsells: ['old_customer_reactivation'],
  },
  {
    id: 'ai_creative_lab',
    name: 'AI Kreatif & Reklam Test Laboratuvarı',
    category: 'revenue',
    description: 'Reklam kreatifi üretimi + A/B test + kazanan kreatif raporu.',
    targetSectors: ['ecommerce', 'real_estate'],
    problemSolved: 'Reklam bütçesi yanar; kazanan kreatif belirsiz.',
    setupPrice: 12000,
    monthlyPrice: 18000,
    deliveryDays: 10,
    difficulty: 'medium',
    salesPromise: 'Her ay 30+ kreatif, kazanan akışı net.',
    antiPatterns: [],
    checklist: ['Kreatif briefi', 'Üretim sprintı', 'Test ve raporlama'],
    upsells: ['ads_optimization', 'post_purchase_flows'],
  },
  {
    id: 'ads_optimization',
    name: 'Reklam Optimizasyonu',
    category: 'revenue',
    description: 'Meta/Google reklamlarında haftalık optimizasyon, hedefleme, bid yönetimi.',
    targetSectors: ['ecommerce', 'real_estate', 'automotive'],
    problemSolved: 'Reklam panelleri optimize edilmiyor, ROAS düşük.',
    setupPrice: 8000,
    monthlyPrice: 14000,
    deliveryDays: 5,
    difficulty: 'medium',
    salesPromise: 'ROAS\'ı %20+ iyileştirme hedefi.',
    antiPatterns: [],
    checklist: ['Hesap audit', 'Optimizasyon sprintları', 'Aylık rapor'],
    upsells: ['ai_creative_lab'],
  },
  {
    id: 'post_purchase_flows',
    name: 'Post-Purchase Akışları',
    category: 'revenue',
    description: 'Satın alma sonrası teşekkür, çapraz satış, sadakat akışları.',
    targetSectors: ['ecommerce'],
    problemSolved: 'İlk siparişten sonra müşteri kayıp gidiyor.',
    setupPrice: 7000,
    monthlyPrice: 9000,
    deliveryDays: 7,
    difficulty: 'low',
    salesPromise: 'Tekrar satın alma oranını yükseltin.',
    antiPatterns: [],
    checklist: ['Email/WA akışı', 'Sadakat tetikleri', 'Rapor'],
    upsells: ['crm_reactivation'],
  },
  {
    id: 'review_engine',
    name: 'Review Engine',
    category: 'revenue',
    description: 'Google/Yandex/TripAdvisor yorum toplama otomasyonu.',
    targetSectors: ['health_clinic', 'tourism', 'beauty', 'automotive'],
    problemSolved: 'Yeterli yorum yok → dönüşüm düşük, güven zayıf.',
    setupPrice: 5000,
    monthlyPrice: 7500,
    deliveryDays: 5,
    difficulty: 'low',
    salesPromise: '90 günde yorum sayınızı 3X.',
    antiPatterns: ['Fake yorum vaat etme'],
    checklist: ['QR + link akışı', 'Hatırlatma mesajı', 'Yorum raporu'],
    upsells: ['appointment_recovery'],
  },

  {
    id: 'document_automation',
    name: 'Belge İşleme Otomasyonu',
    category: 'operations',
    description: 'PDF/Excel/Word belge işleme, sınıflandırma, klasörleme.',
    targetSectors: ['accounting', 'logistics'],
    problemSolved: 'Saatlerce manuel belge işleniyor.',
    setupPrice: 12000,
    monthlyPrice: 14000,
    deliveryDays: 14,
    difficulty: 'high',
    salesPromise: 'Belge işleme süresini %70 azaltın.',
    antiPatterns: [],
    checklist: ['Belge tipleri', 'OCR + sınıflama', 'Entegrasyon'],
    upsells: ['document_tracking'],
  },
  {
    id: 'document_tracking',
    name: 'Evrak Takip Sistemi',
    category: 'operations',
    description: 'Müşteri evrakları, eksik belgeler, son tarih uyarıları.',
    targetSectors: ['accounting'],
    problemSolved: 'Eksik evrak müşteri başına kayboluyor.',
    setupPrice: 8000,
    monthlyPrice: 9000,
    deliveryDays: 10,
    difficulty: 'medium',
    salesPromise: 'Hiçbir müşteri evrakı unutulmasın.',
    antiPatterns: [],
    checklist: ['Müşteri panel', 'Eksik liste', 'Hatırlatma'],
    upsells: ['client_status_bot'],
  },
  {
    id: 'client_status_bot',
    name: 'Müşteri Status Bot',
    category: 'operations',
    description: 'Müşteri "durumum ne?" sorularına otomatik yanıt.',
    targetSectors: ['accounting', 'logistics'],
    problemSolved: 'Aynı soru her gün tekrarlanıyor.',
    setupPrice: 6000,
    monthlyPrice: 7000,
    deliveryDays: 7,
    difficulty: 'low',
    salesPromise: 'Müşteri sorularını otomatik cevapla.',
    antiPatterns: [],
    checklist: ['Veri kaynağı bağlama', 'WA/email kanalı', 'Test'],
    upsells: ['document_tracking'],
  },
  {
    id: 'operations_dashboard',
    name: 'Operasyon Dashboard',
    category: 'operations',
    description: 'Sevkiyat, sipariş, teslimat KPI paneli.',
    targetSectors: ['logistics', 'ecommerce'],
    problemSolved: 'Operasyon görünmüyor, ateş söndürmekle vakit kaybediliyor.',
    setupPrice: 10000,
    monthlyPrice: 8000,
    deliveryDays: 14,
    difficulty: 'medium',
    salesPromise: 'Operasyonu tek panelden yönetin.',
    antiPatterns: [],
    checklist: ['KPI tanımı', 'Veri kaynağı', 'Panel'],
    upsells: [],
  },
  {
    id: 'crm_reactivation',
    name: 'CRM Temizleme & Segmentasyon',
    category: 'operations',
    description: 'Karışık CRM\'i temizle, segment et, aktive et.',
    targetSectors: ['ecommerce', 'insurance', 'real_estate'],
    problemSolved: 'CRM\'de binlerce kayıt var, kullanılmıyor.',
    setupPrice: 9000,
    monthlyPrice: 6000,
    deliveryDays: 14,
    difficulty: 'medium',
    salesPromise: 'CRM\'iniz canlanır, segment bazlı kampanya başlar.',
    antiPatterns: [],
    checklist: ['Veri denetimi', 'Segmentasyon', 'Aktivasyon kampanyası'],
    upsells: ['old_customer_reactivation'],
  },
  {
    id: 'lead_tracking',
    name: 'Lead Takip Sistemi',
    category: 'revenue',
    description: 'Çoklu kaynaktan gelen lead\'leri tek panelden takip.',
    targetSectors: ['real_estate', 'automotive', 'education'],
    problemSolved: 'Lead\'ler Excel/email/WA arasında kayboluyor.',
    setupPrice: 9000,
    monthlyPrice: 10000,
    deliveryDays: 10,
    difficulty: 'medium',
    salesPromise: 'Tek panelden tüm lead\'leriniz, hiçbiri kaçmaz.',
    antiPatterns: [],
    checklist: ['Kaynak entegrasyonu', 'Pipeline', 'Rapor'],
    upsells: ['followup_agent', 'proposal_desk'],
  },
  {
    id: 'portfolio_matching',
    name: 'Portföy Eşleştirme',
    category: 'revenue',
    description: 'Lead profili ↔ portföy stoku otomatik eşleştirme.',
    targetSectors: ['real_estate'],
    problemSolved: 'Müşteri profiline uygun portföy bulmak el yapımı iş.',
    setupPrice: 8000,
    monthlyPrice: 9000,
    deliveryDays: 10,
    difficulty: 'medium',
    salesPromise: 'Müşteriye 5 dakikada 3 uygun portföy.',
    antiPatterns: [],
    checklist: ['Portföy şeması', 'Eşleşme algoritması', 'Sunum şablonu'],
    upsells: ['proposal_desk'],
  },
  {
    id: 'lead_to_test_drive',
    name: 'Lead → Test Sürüşü',
    category: 'revenue',
    description: 'Lead\'i test sürüşü randevusuna taşıyan akış.',
    targetSectors: ['automotive'],
    problemSolved: 'Lead\'ler arada kayboluyor, test sürüşüne dönmüyor.',
    setupPrice: 7000,
    monthlyPrice: 9000,
    deliveryDays: 7,
    difficulty: 'low',
    salesPromise: 'Lead\'in %25\'i test sürüşüne, %40\'ı satışa.',
    antiPatterns: [],
    checklist: ['Akış', 'Randevu sistemi', 'Hatırlatma'],
    upsells: ['service_reminder', 'old_customer_reactivation'],
  },
  {
    id: 'service_reminder',
    name: 'Servis Hatırlatma',
    category: 'revenue',
    description: 'Bakım/servis hatırlatma + kampanya.',
    targetSectors: ['automotive'],
    problemSolved: 'Müşteri başka servise gidiyor.',
    setupPrice: 5000,
    monthlyPrice: 7000,
    deliveryDays: 5,
    difficulty: 'low',
    salesPromise: 'Servis dönüş oranını artırın.',
    antiPatterns: [],
    checklist: ['Liste', 'Hatırlatma akışı'],
    upsells: ['old_customer_reactivation'],
  },
  {
    id: 'parent_tracking',
    name: 'Veli Takip Sistemi',
    category: 'revenue',
    description: 'Veli adayı ile iletişim, bilgilendirme, deneme ders akışı.',
    targetSectors: ['education'],
    problemSolved: 'Veliler sorularını farklı kanallardan soruyor, takip kayboluyor.',
    setupPrice: 8000,
    monthlyPrice: 9000,
    deliveryDays: 10,
    difficulty: 'medium',
    salesPromise: 'Tek panelden tüm veli iletişimi.',
    antiPatterns: [],
    checklist: ['Kanal birleştirme', 'Akış', 'Rapor'],
    upsells: ['enrollment_pipeline'],
  },
  {
    id: 'enrollment_pipeline',
    name: 'Kayıt Pipeline',
    category: 'revenue',
    description: 'Veli adayı → tanıtım → deneme → kayıt akışı.',
    targetSectors: ['education'],
    problemSolved: 'Kayıt dönemi kaotik, lead kayboluyor.',
    setupPrice: 8000,
    monthlyPrice: 8000,
    deliveryDays: 10,
    difficulty: 'low',
    salesPromise: 'Kayıt sezonunu düzenli pipeline\'a alın.',
    antiPatterns: [],
    checklist: ['Stage tanımı', 'Otomatik geçiş', 'Rapor'],
    upsells: ['parent_tracking'],
  },
  {
    id: 'reservation_tracking',
    name: 'Rezervasyon Takip',
    category: 'revenue',
    description: 'Rezervasyon hatırlatma, gelmeyen müşteri için yeniden teklif.',
    targetSectors: ['tourism'],
    problemSolved: 'Rezervasyonlar düşüyor, boş kalan kontenjan.',
    setupPrice: 7000,
    monthlyPrice: 8000,
    deliveryDays: 7,
    difficulty: 'low',
    salesPromise: 'Doluluk oranını artırın.',
    antiPatterns: [],
    checklist: ['Hatırlatma', 'Yeniden teklif akışı'],
    upsells: ['loyalty_system', 'review_engine'],
  },
  {
    id: 'loyalty_system',
    name: 'Sadakat Sistemi',
    category: 'revenue',
    description: 'Tekrar ziyaret kampanyaları, puan sistemi.',
    targetSectors: ['tourism', 'ecommerce'],
    problemSolved: 'Müşteri bir kez geliyor, bir daha dönmüyor.',
    setupPrice: 9000,
    monthlyPrice: 10000,
    deliveryDays: 14,
    difficulty: 'medium',
    salesPromise: 'Tekrar gelen müşteri oranınızı yükseltin.',
    antiPatterns: [],
    checklist: ['Sadakat kuralları', 'Kampanya akışı'],
    upsells: ['review_engine'],
  },

  {
    id: 'social_media_pack',
    name: 'Sosyal Medya Tasarım Paketi',
    category: 'creative',
    description: 'Aylık sosyal medya tasarımları + içerik takvimi.',
    targetSectors: ['beauty', 'tourism', 'ecommerce', 'health_clinic'],
    problemSolved: 'Sosyal medyada düzenli içerik yok.',
    setupPrice: 4000,
    monthlyPrice: 7000,
    deliveryDays: 7,
    difficulty: 'low',
    salesPromise: 'Her ay 20+ profesyonel tasarım.',
    antiPatterns: [],
    checklist: ['Stil rehberi', 'İçerik takvimi', 'Aylık teslim'],
    upsells: ['review_engine'],
  },
  {
    id: 'brand_identity',
    name: 'Logo & Marka Kimliği',
    category: 'creative',
    description: 'Logo + renk paleti + tipografi + temel kullanım kılavuzu.',
    targetSectors: [],
    problemSolved: 'Marka kimliği tutarsız.',
    setupPrice: 15000,
    monthlyPrice: 0,
    deliveryDays: 14,
    difficulty: 'medium',
    salesPromise: 'Tutarlı, profesyonel marka kimliği.',
    antiPatterns: [],
    checklist: ['Keşif', 'Konsept', 'Final teslim'],
    upsells: ['corporate_identity', 'website'],
  },
  {
    id: 'corporate_identity',
    name: 'Kurumsal Kimlik',
    category: 'creative',
    description: 'Kartvizit, antetli kağıt, evrak şablonları, sunum şablonu.',
    targetSectors: [],
    problemSolved: 'Kurumsal evrak ve materyal eksik.',
    setupPrice: 12000,
    monthlyPrice: 0,
    deliveryDays: 10,
    difficulty: 'low',
    salesPromise: 'Tam set kurumsal evrak.',
    antiPatterns: [],
    checklist: ['Şablonlar', 'Baskı dosyaları'],
    upsells: ['website'],
  },
  {
    id: 'website',
    name: 'Web Sitesi',
    category: 'creative',
    description: 'Tek sayfa / kurumsal web sitesi.',
    targetSectors: [],
    problemSolved: 'Web sitesi yok veya çok eski.',
    setupPrice: 25000,
    monthlyPrice: 1500,
    deliveryDays: 21,
    difficulty: 'medium',
    salesPromise: 'Modern, hızlı, mobil uyumlu web sitesi.',
    antiPatterns: [],
    checklist: ['Mimari', 'Tasarım', 'Geliştirme', 'Yayın'],
    upsells: ['ads_optimization', 'review_engine'],
  },
]

export function findOfferById(id: string): Offer | undefined {
  return OFFERS.find(o => o.id === id)
}

export function offersByCategory(category: Offer['category']): Offer[] {
  return OFFERS.filter(o => o.category === category)
}

export function offersForSector(sectorId: string): Offer[] {
  return OFFERS.filter(o => o.targetSectors.includes(sectorId))
}
