// Kanonik hizmet kataloğu (v2 read model) — Lead Intelligence v2.
//
// ÜÇ legacy kaynak (offers.ts 30 kayıt, seed-playbooks DEFAULT_PLAYBOOKS 21 kayıt,
// migration 002 SQL seed 15 kayıt) burada TEK kanonik slug setine deduplike edilir.
// Bu bir "compatibility adapter"dır: legacy kaynaklar YERİNDE kalır ve SALT-OKUNUR
// tüketilir; v2 kodu legacy'ye asla yazmaz. Tam konsolidasyon post-cutover işidir.
//
// Fiyat kuralı: offers.ts'te karşılığı olan paketler fiyatı ORADAN alır (tek fiyat
// kaynağı) — findOfferById ile sarılır. Playbook-only paketler seed fiyatını taşır.
// Panel yalnız fiyat + aktiflik override edebilir (service_catalog tablosu,
// catalogOverrides.getCatalog merge eder).
//
// Satış metni kuralı: salesCopy alanlarında kanıtsız %/ROI/kat vaadi YASAK —
// catalog.test.ts UNPROVEN_CLAIM_RE ile lint'ler.

import { ServiceDomain, ServiceFamily, ServicePackage } from '../types'
import { findOfferById } from '../offers'

export const SERVICE_FAMILIES: ServiceFamily[] = [
  // Tasarım
  { id: 'marka', domain: 'tasarim', name: 'Marka & Kimlik' },
  { id: 'web', domain: 'tasarim', name: 'Web Tasarım' },
  { id: 'sosyal', domain: 'tasarim', name: 'Sosyal Medya Tasarımı' },
  { id: 'baski-grafik', domain: 'tasarim', name: 'Baskı & Grafik' },
  { id: 'reklam-gorsel', domain: 'tasarim', name: 'Reklam Görselleri' },
  // AI & Otomasyon
  { id: 'satis-asistani', domain: 'ai_otomasyon', name: 'AI Satış Asistanları' },
  { id: 'randevu-yorum', domain: 'ai_otomasyon', name: 'Randevu & Yorum' },
  { id: 'musteri-canlandirma', domain: 'ai_otomasyon', name: 'Müşteri Canlandırma' },
  { id: 'operasyon', domain: 'ai_otomasyon', name: 'Operasyon Otomasyonu' },
  { id: 'lead-pipeline', domain: 'ai_otomasyon', name: 'Lead & Pipeline' },
  { id: 'sektor-akislari', domain: 'ai_otomasyon', name: 'Sektör Akışları' },
  // Hibrit
  { id: 'buyume-paketi', domain: 'hibrit', name: 'Büyüme Paketleri' },
  { id: 'dijital-varlik', domain: 'hibrit', name: 'Dijital Varlık' },
]

// Fiyatı offers.ts'ten çeken yardımcı — offer yoksa fallback (test bunu yakalar).
function offerPrice(offerId: string): { setup: number; monthly: number; days: number } {
  const o = findOfferById(offerId)
  if (!o) return { setup: 0, monthly: 0, days: 7 }
  return { setup: o.setupPrice, monthly: o.monthlyPrice, days: o.deliveryDays }
}

const p = offerPrice // kısaltma

export const SERVICE_PACKAGES: ServicePackage[] = [
  // ══════════════════════ TASARIM ══════════════════════
  {
    slug: 'logo-marka-kimligi',
    familyId: 'marka',
    name: 'Logo & Marka Kimliği',
    description: 'Logo + renk paleti + tipografi + temel kullanım kılavuzu.',
    defaultSetupPriceTl: p('brand_identity').setup,
    defaultMonthlyPriceTl: p('brand_identity').monthly,
    deliveryDays: p('brand_identity').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Tutarlı, profesyonel marka kimliği — her temas noktasında aynı görünüm.',
      antiPatterns: ['Logoyu tek başına satma — kimlik sistemiyle birlikte anlat'],
      checklist: ['Keşif', 'Konsept', 'Final teslim', 'Kullanım kılavuzu'],
    },
    requiredEvidenceKinds: ['screenshot', 'html_signal', 'places_data'],
    targetSectors: [],
    upsellSlugs: ['kurumsal-kimlik', 'web-sitesi'],
    legacyOfferIds: ['brand_identity'],
    legacyPlaybookNames: ['Logo & Marka Kimliği', 'Marka Rehberi (Brand Guideline)'],
  },
  {
    slug: 'kurumsal-kimlik',
    familyId: 'marka',
    name: 'Kurumsal Kimlik Paketi',
    description: 'Kartvizit, antetli kağıt, evrak şablonları, sunum şablonu.',
    defaultSetupPriceTl: p('corporate_identity').setup,
    defaultMonthlyPriceTl: p('corporate_identity').monthly,
    deliveryDays: p('corporate_identity').days,
    difficulty: 'low',
    salesCopy: {
      promise: 'Tam set kurumsal evrak — tek seferlik yatırım, yıllarca kullanım.',
      antiPatterns: [],
      checklist: ['Şablonlar', 'Baskı dosyaları', 'Dijital versiyonlar'],
    },
    requiredEvidenceKinds: ['screenshot', 'html_signal', 'places_data'],
    targetSectors: [],
    upsellSlugs: ['web-sitesi'],
    legacyOfferIds: ['corporate_identity'],
    legacyPlaybookNames: ['Kurumsal Kimlik Paketi'],
  },
  {
    slug: 'web-sitesi',
    familyId: 'web',
    name: 'Web Sitesi',
    description: 'Tek sayfa / kurumsal web sitesi — modern, hızlı, mobil uyumlu.',
    defaultSetupPriceTl: p('website').setup,
    defaultMonthlyPriceTl: p('website').monthly,
    deliveryDays: p('website').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Modern, hızlı, mobil uyumlu web sitesi — mevcut sitenizin somut eksikleri üzerinden konuşuruz.',
      antiPatterns: ['Genel "siteniz eski" söylemi yerine ölçülmüş kusur göster'],
      checklist: ['Mimari', 'Tasarım', 'Geliştirme', 'Yayın'],
    },
    requiredEvidenceKinds: ['screenshot', 'pagespeed', 'html_signal'],
    targetSectors: [],
    upsellSlugs: ['google-isletme-profili', 'yorum-motoru'],
    legacyOfferIds: ['website'],
    legacyPlaybookNames: ['Web Sitesi Tasarımı'],
  },
  {
    slug: 'sosyal-medya-paketi',
    familyId: 'sosyal',
    name: 'Sosyal Medya Tasarım Paketi',
    description: 'Aylık sosyal medya tasarımları + içerik takvimi (12 post + 12 story + 4 carousel).',
    defaultSetupPriceTl: p('social_media_pack').setup,
    defaultMonthlyPriceTl: p('social_media_pack').monthly,
    deliveryDays: p('social_media_pack').days,
    difficulty: 'low',
    salesCopy: {
      promise: 'Her ay düzenli, profesyonel görsel üretim — takvimli, markanıza özel.',
      antiPatterns: [],
      checklist: ['Stil rehberi', 'İçerik takvimi', 'Aylık teslim'],
    },
    requiredEvidenceKinds: ['html_signal', 'places_data'],
    targetSectors: ['beauty', 'tourism', 'ecommerce', 'health_clinic'],
    upsellSlugs: ['yorum-motoru', 'sosyal-medya-sablon-seti'],
    legacyOfferIds: ['social_media_pack'],
    legacyPlaybookNames: ['Sosyal Medya Yönetimi'],
  },
  {
    slug: 'sosyal-medya-sablon-seti',
    familyId: 'sosyal',
    name: 'Sosyal Medya Şablon Seti',
    description: 'İşletmeye özel Canva/PSD şablonları — ekip kendi başına düzenleyip yayınlar.',
    defaultSetupPriceTl: 3500,
    defaultMonthlyPriceTl: 0,
    deliveryDays: 7,
    difficulty: 'low',
    salesCopy: {
      promise: 'Hazır şablon setiyle ekibiniz dakikalar içinde markaya uygun içerik üretir.',
      antiPatterns: [],
      checklist: ['Marka analizi', 'Şablon seti (10 adet)', 'Kullanım rehberi'],
    },
    requiredEvidenceKinds: ['html_signal', 'places_data'],
    targetSectors: [],
    upsellSlugs: ['sosyal-medya-paketi'],
    legacyOfferIds: [],
    legacyPlaybookNames: ['Sosyal Medya Şablon Seti', 'Sosyal Medya İçerik Şablonları'],
  },
  {
    slug: 'instagram-profil-optimizasyonu',
    familyId: 'sosyal',
    name: 'Instagram Profil Optimizasyonu',
    description: 'Bio, highlight tasarımı, profil fotoğrafı, link-in-bio kurulumu.',
    defaultSetupPriceTl: 2500,
    defaultMonthlyPriceTl: 0,
    deliveryDays: 5,
    difficulty: 'low',
    salesCopy: {
      promise: 'Profiliniz ilk bakışta güven versin — dönüşüm odaklı vitrin düzeni.',
      antiPatterns: [],
      checklist: ['Profil analizi', 'Bio yazımı', 'Highlight kapakları', 'Link-in-bio'],
    },
    requiredEvidenceKinds: ['html_signal', 'places_data'],
    targetSectors: ['beauty', 'tourism', 'ecommerce'],
    upsellSlugs: ['sosyal-medya-paketi'],
    legacyOfferIds: [],
    legacyPlaybookNames: ['Instagram Profil Optimizasyonu'],
  },
  {
    slug: 'ambalaj-etiket',
    familyId: 'baski-grafik',
    name: 'Ambalaj & Etiket Tasarımı',
    description: 'Ürün ambalajı, etiket, sticker — baskıya hazır dosyalarla teslim.',
    defaultSetupPriceTl: 5000,
    defaultMonthlyPriceTl: 0,
    deliveryDays: 10,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Rafta göze çarpan, markayı taşıyan ambalaj tasarımı.',
      antiPatterns: [],
      checklist: ['Ürün analizi', 'Konsept', 'Revizyon', 'Baskı dosyası'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['ecommerce'],
    upsellSlugs: ['logo-marka-kimligi'],
    legacyOfferIds: [],
    legacyPlaybookNames: ['Ambalaj & Etiket Tasarımı'],
  },
  {
    slug: 'brosur-katalog',
    familyId: 'baski-grafik',
    name: 'Broşür, Katalog & İnfografik',
    description: 'Ürün/hizmet katalogları, tanıtım broşürleri, veri görselleştirme.',
    defaultSetupPriceTl: 3500,
    defaultMonthlyPriceTl: 0,
    deliveryDays: 7,
    difficulty: 'low',
    salesCopy: {
      promise: 'Müşteride kalan materyal sizi temsil eder — baskı ve dijital tek pakette.',
      antiPatterns: [],
      checklist: ['İçerik toplama', 'Düzen tasarımı', 'Baskı + dijital teslim'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: [],
    upsellSlugs: ['kurumsal-kimlik'],
    legacyOfferIds: [],
    legacyPlaybookNames: ['Broşür & Katalog Tasarımı', 'İnfografik & Data Görselleştirme'],
  },
  {
    slug: 'sunum-pitch-deck',
    familyId: 'baski-grafik',
    name: 'Sunum & Pitch Deck Tasarımı',
    description: 'Yatırımcı/müşteri sunumları için profesyonel deck tasarımı.',
    defaultSetupPriceTl: 4000,
    defaultMonthlyPriceTl: 0,
    deliveryDays: 7,
    difficulty: 'low',
    salesCopy: {
      promise: 'Güçlü fikre yakışan sunum — kurgu, hiyerarşi ve görsel dil bizden.',
      antiPatterns: [],
      checklist: ['İçerik analizi', 'Şablon', 'Slayt kurgusu', 'Teslim'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: [],
    upsellSlugs: ['kurumsal-kimlik'],
    legacyOfferIds: [],
    legacyPlaybookNames: ['Sunum & Pitch Deck Tasarımı'],
  },
  {
    slug: 'dijital-reklam-gorselleri',
    familyId: 'reklam-gorsel',
    name: 'Dijital Reklam Görselleri',
    description: 'Meta/Google/LinkedIn için tüm formatlarda reklam görseli + varyasyonlar.',
    defaultSetupPriceTl: 3000,
    defaultMonthlyPriceTl: 2500,
    deliveryDays: 5,
    difficulty: 'low',
    salesCopy: {
      promise: 'Dönüşüm odaklı reklam görselleri — test için varyasyonlarıyla.',
      antiPatterns: [],
      checklist: ['Hedef kitle analizi', 'Konsept', 'Tüm formatlar', 'Varyasyonlar'],
    },
    requiredEvidenceKinds: ['html_signal', 'places_data'],
    targetSectors: ['ecommerce', 'real_estate', 'automotive'],
    upsellSlugs: ['reklam-optimizasyonu', 'ai-kreatif-lab'],
    legacyOfferIds: [],
    legacyPlaybookNames: ['Dijital Reklam Görselleri'],
  },

  // ══════════════════════ AI & OTOMASYON ══════════════════════
  {
    slug: 'ai-satis-asistani',
    familyId: 'satis-asistani',
    name: 'AI Satış Asistanı (WhatsApp/Instagram)',
    description: '7/24 soru yanıtlama, randevu alma, müşteri bilgisi toplama, fiyat bilgisi ve upsell.',
    defaultSetupPriceTl: p('ai_sales_assistant').setup,
    defaultMonthlyPriceTl: p('ai_sales_assistant').monthly,
    deliveryDays: p('ai_sales_assistant').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Müşteri sorularına saniyeler içinde yanıt, otomatik randevu ve bilgi toplama.',
      antiPatterns: [
        '"Chatbot satıyoruz" diye başlama — kaybedilen randevu/satış üzerinden anlat',
        'Teknik terimle değil, kazanılan zamanla sat',
      ],
      checklist: [
        'SSS + fiyat listesi + randevu kuralları toplandı',
        'WhatsApp Business / Instagram DM entegrasyonu',
        'Randevu ve bilgi toplama akışı test edildi',
        'İlk hafta yanıt kalitesi raporu',
      ],
    },
    requiredEvidenceKinds: ['review_signal', 'places_data', 'html_signal'],
    targetSectors: ['beauty', 'health_clinic', 'real_estate', 'automotive', 'ecommerce', 'education'],
    upsellSlugs: ['randevu-kurtarma', 'yorum-motoru', 'sosyal-medya-paketi'],
    legacyOfferIds: ['ai_sales_assistant', 'whatsapp_sales_assistant'],
    legacyPlaybookNames: ['AI Chatbot Kurulumu'],
  },
  {
    slug: 'hizli-lead-yaniti',
    familyId: 'satis-asistani',
    name: 'Hızlı Lead Yanıtı',
    description: "Reklam/form/WhatsApp lead'lerine dakikalar içinde otomatik dönüş.",
    defaultSetupPriceTl: p('ai_lead_response').setup,
    defaultMonthlyPriceTl: p('ai_lead_response').monthly,
    deliveryDays: p('ai_lead_response').days,
    difficulty: 'medium',
    salesCopy: {
      promise: "Her lead'e dakikalar içinde dönüş — geç kalan yanıt rakibe gider.",
      antiPatterns: ['"AI bot satıyoruz" diye başlama', 'Teknik özellikle değil, kaçan fırsatla anlat'],
      checklist: ['Lead kanalları haritalandı', 'Yanıt şablonları', 'Entegrasyon', 'İlk hafta raporu'],
    },
    requiredEvidenceKinds: ['cta_analysis', 'form_analysis', 'html_signal'],
    targetSectors: ['health_clinic', 'real_estate', 'automotive', 'education', 'insurance'],
    upsellSlugs: ['takip-zincirleri', 'randevu-kurtarma'],
    legacyOfferIds: ['ai_lead_response'],
    legacyPlaybookNames: ['Hızlı Lead Yanıtı'],
  },
  {
    slug: 'takip-zincirleri',
    familyId: 'satis-asistani',
    name: 'Takip Zincirleri',
    description: 'Yanıtsız lead ve teklif sonrası otomatik takip dizileri (WA/SMS/e-posta).',
    defaultSetupPriceTl: p('followup_agent').setup,
    defaultMonthlyPriceTl: p('followup_agent').monthly,
    deliveryDays: p('followup_agent').days,
    difficulty: 'low',
    salesCopy: {
      promise: 'Sessiz kalan lead kendiliğinden takip edilir — unutulan fırsat kalmaz.',
      antiPatterns: [],
      checklist: ['Takip mesaj dizisi', 'Kanal seçimi', 'Performans ölçümü'],
    },
    requiredEvidenceKinds: ['cta_analysis', 'form_analysis'],
    targetSectors: ['health_clinic', 'real_estate', 'insurance', 'education', 'automotive'],
    upsellSlugs: ['hizli-lead-yaniti', 'teklif-masasi'],
    legacyOfferIds: ['followup_agent'],
    legacyPlaybookNames: ['Takip Zincirleri', 'E-posta Otomasyon Sistemi'],
  },
  {
    slug: 'randevu-kurtarma',
    familyId: 'randevu-yorum',
    name: 'Randevu Kurtarma Sistemi',
    description: 'No-show önleme, hatırlatma, yeniden randevulandırma.',
    defaultSetupPriceTl: p('appointment_recovery').setup,
    defaultMonthlyPriceTl: p('appointment_recovery').monthly,
    deliveryDays: p('appointment_recovery').days,
    difficulty: 'low',
    salesCopy: {
      promise: 'Gelmeyen randevu kendiliğinden telafi edilir — boş koltuk azalır.',
      antiPatterns: [],
      checklist: ['Hatırlatma akışı', 'No-show sonrası yeniden randevu', 'Aylık rapor'],
    },
    requiredEvidenceKinds: ['places_data', 'review_signal'],
    targetSectors: ['health_clinic', 'beauty', 'automotive'],
    upsellSlugs: ['yorum-motoru', 'takip-zincirleri'],
    legacyOfferIds: ['appointment_recovery'],
    legacyPlaybookNames: ['Randevu Asistanı (Diyetisyen & Klinik)'],
  },
  {
    slug: 'yorum-motoru',
    familyId: 'randevu-yorum',
    name: 'Yorum Motoru',
    description: 'Google/Yandex/TripAdvisor yorum toplama otomasyonu + yorum analitiği.',
    defaultSetupPriceTl: p('review_engine').setup,
    defaultMonthlyPriceTl: p('review_engine').monthly,
    deliveryDays: p('review_engine').days,
    difficulty: 'low',
    salesCopy: {
      promise: 'Memnun müşteriden düzenli, gerçek yorum akışı — görünürlük ve güven.',
      antiPatterns: ['Fake yorum vaat etme'],
      checklist: ['QR + link akışı', 'Hatırlatma mesajı', 'Yorum raporu'],
    },
    requiredEvidenceKinds: ['review_signal', 'places_data'],
    targetSectors: ['health_clinic', 'tourism', 'beauty', 'automotive'],
    upsellSlugs: ['randevu-kurtarma'],
    legacyOfferIds: ['review_engine'],
    legacyPlaybookNames: ['E-Ticaret Yorum Analitiği & Destek'],
  },
  {
    slug: 'eski-musteri-canlandirma',
    familyId: 'musteri-canlandirma',
    name: 'Eski Müşteri / Eski Hasta Canlandırma',
    description: 'Geçmiş müşteri/hasta listelerine segment bazlı yeniden aktivasyon kampanyası.',
    defaultSetupPriceTl: p('old_customer_reactivation').setup,
    defaultMonthlyPriceTl: p('old_customer_reactivation').monthly,
    deliveryDays: p('old_customer_reactivation').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Ölü duran müşteri listesi segmentli kampanyayla yeniden gelir üretir.',
      antiPatterns: ['Yeni müşteri kazanma odaklı sektörlerde ön plana koymama'],
      checklist: ['Liste temizleme + segmentasyon', 'Mesaj akışı', 'İlk kampanya', 'Dönüş raporu'],
    },
    requiredEvidenceKinds: ['places_data', 'review_signal'],
    targetSectors: ['health_clinic', 'automotive', 'insurance', 'ecommerce'],
    upsellSlugs: ['crm-temizleme-segmentasyon', 'yorum-motoru'],
    legacyOfferIds: ['old_customer_reactivation', 'old_patient_reactivation'],
    legacyPlaybookNames: ['Eski Müşteri Canlandırma'],
  },
  {
    slug: 'crm-temizleme-segmentasyon',
    familyId: 'musteri-canlandirma',
    name: 'CRM Temizleme & Segmentasyon',
    description: "Karışık CRM'i temizle, segment et, aktive et.",
    defaultSetupPriceTl: p('crm_reactivation').setup,
    defaultMonthlyPriceTl: p('crm_reactivation').monthly,
    deliveryDays: p('crm_reactivation').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'CRM canlanır, segment bazlı kampanya düzeni kurulur.',
      antiPatterns: [],
      checklist: ['Veri denetimi', 'Segmentasyon', 'Aktivasyon kampanyası'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['ecommerce', 'insurance', 'real_estate'],
    upsellSlugs: ['eski-musteri-canlandirma'],
    legacyOfferIds: ['crm_reactivation'],
    legacyPlaybookNames: [],
  },
  {
    slug: 'yenileme-motoru',
    familyId: 'musteri-canlandirma',
    name: 'Yenileme Motoru',
    description: 'Poliçe/abonelik yenileme otomasyonu, çapraz satış önerileri.',
    defaultSetupPriceTl: p('renewal_engine').setup,
    defaultMonthlyPriceTl: p('renewal_engine').monthly,
    deliveryDays: p('renewal_engine').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Yenileme tarihi gelen hiçbir müşteri unutulmaz.',
      antiPatterns: [],
      checklist: ['Yenileme listesi', 'Hatırlatma + çapraz satış akışı', 'Aylık rapor'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['insurance'],
    upsellSlugs: ['eski-musteri-canlandirma'],
    legacyOfferIds: ['renewal_engine'],
    legacyPlaybookNames: [],
  },
  {
    slug: 'sadakat-sistemi',
    familyId: 'musteri-canlandirma',
    name: 'Sadakat Sistemi',
    description: 'Tekrar ziyaret kampanyaları, puan sistemi.',
    defaultSetupPriceTl: p('loyalty_system').setup,
    defaultMonthlyPriceTl: p('loyalty_system').monthly,
    deliveryDays: p('loyalty_system').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Bir kez gelen müşteriyi düzenli müşteriye çeviren kurgular.',
      antiPatterns: [],
      checklist: ['Sadakat kuralları', 'Kampanya akışı'],
    },
    requiredEvidenceKinds: ['places_data', 'review_signal'],
    targetSectors: ['tourism', 'ecommerce'],
    upsellSlugs: ['yorum-motoru'],
    legacyOfferIds: ['loyalty_system'],
    legacyPlaybookNames: [],
  },
  {
    slug: 'satis-sonrasi-akislar',
    familyId: 'musteri-canlandirma',
    name: 'Satış Sonrası Akışlar',
    description: 'Satın alma sonrası teşekkür, çapraz satış, sadakat akışları.',
    defaultSetupPriceTl: p('post_purchase_flows').setup,
    defaultMonthlyPriceTl: p('post_purchase_flows').monthly,
    deliveryDays: p('post_purchase_flows').days,
    difficulty: 'low',
    salesCopy: {
      promise: 'İlk siparişten sonra müşteri kaybolmaz — akışlar devreye girer.',
      antiPatterns: [],
      checklist: ['Email/WA akışı', 'Sadakat tetikleri', 'Rapor'],
    },
    requiredEvidenceKinds: ['html_signal'],
    targetSectors: ['ecommerce'],
    upsellSlugs: ['crm-temizleme-segmentasyon'],
    legacyOfferIds: ['post_purchase_flows'],
    legacyPlaybookNames: [],
  },
  {
    slug: 'belge-otomasyonu',
    familyId: 'operasyon',
    name: 'Belge İşleme Otomasyonu',
    description: 'PDF/Excel/Word belge işleme, OCR, sınıflandırma, klasörleme.',
    defaultSetupPriceTl: p('document_automation').setup,
    defaultMonthlyPriceTl: p('document_automation').monthly,
    deliveryDays: p('document_automation').days,
    difficulty: 'high',
    salesCopy: {
      promise: 'Saatler süren manuel belge işi otomatik akışa döner.',
      antiPatterns: [],
      checklist: ['Belge tipleri', 'OCR + sınıflama', 'Entegrasyon'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['accounting', 'logistics'],
    upsellSlugs: ['evrak-takip'],
    legacyOfferIds: ['document_automation'],
    legacyPlaybookNames: ['Belge İşleme Otomasyonu', 'Mali Müşavir & Vergi OCR', 'Sözleşme Analist & Hukuk Danışman AI'],
  },
  {
    slug: 'evrak-takip',
    familyId: 'operasyon',
    name: 'Evrak Takip Sistemi',
    description: 'Müşteri evrakları, eksik belgeler, son tarih uyarıları.',
    defaultSetupPriceTl: p('document_tracking').setup,
    defaultMonthlyPriceTl: p('document_tracking').monthly,
    deliveryDays: p('document_tracking').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Hiçbir müşteri evrakı unutulmasın — eksikler kendiliğinden bildirilir.',
      antiPatterns: [],
      checklist: ['Müşteri panel', 'Eksik liste', 'Hatırlatma'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['accounting'],
    upsellSlugs: ['musteri-status-bot'],
    legacyOfferIds: ['document_tracking'],
    legacyPlaybookNames: [],
  },
  {
    slug: 'musteri-status-bot',
    familyId: 'operasyon',
    name: 'Müşteri Status Bot',
    description: 'Müşteri "durumum ne?" sorularına otomatik yanıt.',
    defaultSetupPriceTl: p('client_status_bot').setup,
    defaultMonthlyPriceTl: p('client_status_bot').monthly,
    deliveryDays: p('client_status_bot').days,
    difficulty: 'low',
    salesCopy: {
      promise: 'Her gün tekrarlanan durum soruları otomatik yanıtlanır.',
      antiPatterns: [],
      checklist: ['Veri kaynağı bağlama', 'WA/email kanalı', 'Test'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['accounting', 'logistics'],
    upsellSlugs: ['evrak-takip'],
    legacyOfferIds: ['client_status_bot'],
    legacyPlaybookNames: [],
  },
  {
    slug: 'operasyon-dashboard',
    familyId: 'operasyon',
    name: 'Operasyon Dashboard',
    description: 'Sevkiyat, sipariş, teslimat KPI paneli + dahili raporlama.',
    defaultSetupPriceTl: p('operations_dashboard').setup,
    defaultMonthlyPriceTl: p('operations_dashboard').monthly,
    deliveryDays: p('operations_dashboard').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Operasyon tek panelden görünür — ateş söndürme azalır.',
      antiPatterns: [],
      checklist: ['KPI tanımı', 'Veri kaynağı', 'Panel'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['logistics', 'ecommerce'],
    upsellSlugs: [],
    legacyOfferIds: ['operations_dashboard'],
    legacyPlaybookNames: ['Dahili Raporlama'],
  },
  {
    slug: 'lead-takip-sistemi',
    familyId: 'lead-pipeline',
    name: 'Lead Takip Sistemi',
    description: "Çoklu kaynaktan gelen lead'leri tek panelden takip.",
    defaultSetupPriceTl: p('lead_tracking').setup,
    defaultMonthlyPriceTl: p('lead_tracking').monthly,
    deliveryDays: p('lead_tracking').days,
    difficulty: 'medium',
    salesCopy: {
      promise: "Excel/e-posta/WA arasında kaybolan lead'ler tek panelde toplanır.",
      antiPatterns: [],
      checklist: ['Kaynak entegrasyonu', 'Pipeline', 'Rapor'],
    },
    requiredEvidenceKinds: ['cta_analysis', 'form_analysis', 'places_data'],
    targetSectors: ['real_estate', 'automotive', 'education'],
    upsellSlugs: ['takip-zincirleri', 'teklif-masasi'],
    legacyOfferIds: ['lead_tracking'],
    legacyPlaybookNames: ['Lead Generasyon Sistemi'],
  },
  {
    slug: 'teklif-masasi',
    familyId: 'lead-pipeline',
    name: 'Teklif Hazırlama & Takip Masası',
    description: 'Teklif şablonları, otomatik takip, e-imza akışı + outbound metin desteği.',
    defaultSetupPriceTl: p('proposal_desk').setup,
    defaultMonthlyPriceTl: p('proposal_desk').monthly,
    deliveryDays: p('proposal_desk').days,
    difficulty: 'low',
    salesCopy: {
      promise: 'Teklif çıkışı dakikalara iner, takip kendiliğinden yürür.',
      antiPatterns: [],
      checklist: ['Şablonlar', 'Takip dizisi', 'Performans paneli'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['real_estate', 'logistics', 'insurance'],
    upsellSlugs: ['takip-zincirleri'],
    legacyOfferIds: ['proposal_desk'],
    legacyPlaybookNames: ['Outbound Copywriting Ustalığı'],
  },
  {
    slug: 'portfoy-eslestirme',
    familyId: 'sektor-akislari',
    name: 'Portföy Eşleştirme (Emlak)',
    description: 'Lead profili ↔ portföy stoku otomatik eşleştirme + akıllı ilan açıklaması.',
    defaultSetupPriceTl: p('portfolio_matching').setup,
    defaultMonthlyPriceTl: p('portfolio_matching').monthly,
    deliveryDays: p('portfolio_matching').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Müşteri profiline uygun portföy dakikalar içinde önde.',
      antiPatterns: [],
      checklist: ['Portföy şeması', 'Eşleşme algoritması', 'Sunum şablonu'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['real_estate'],
    upsellSlugs: ['teklif-masasi'],
    legacyOfferIds: ['portfolio_matching'],
    legacyPlaybookNames: ['Emlak Portföy & Akıllı Açıklama'],
  },
  {
    slug: 'lead-test-surusu',
    familyId: 'sektor-akislari',
    name: 'Lead → Test Sürüşü (Otomotiv)',
    description: "Lead'i test sürüşü randevusuna taşıyan akış.",
    defaultSetupPriceTl: p('lead_to_test_drive').setup,
    defaultMonthlyPriceTl: p('lead_to_test_drive').monthly,
    deliveryDays: p('lead_to_test_drive').days,
    difficulty: 'low',
    salesCopy: {
      promise: 'Arada kaybolan lead test sürüşü randevusuna bağlanır.',
      antiPatterns: [],
      checklist: ['Akış', 'Randevu sistemi', 'Hatırlatma'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['automotive'],
    upsellSlugs: ['servis-hatirlatma', 'eski-musteri-canlandirma'],
    legacyOfferIds: ['lead_to_test_drive'],
    legacyPlaybookNames: [],
  },
  {
    slug: 'servis-hatirlatma',
    familyId: 'sektor-akislari',
    name: 'Servis Hatırlatma (Otomotiv)',
    description: 'Bakım/servis hatırlatma + kampanya.',
    defaultSetupPriceTl: p('service_reminder').setup,
    defaultMonthlyPriceTl: p('service_reminder').monthly,
    deliveryDays: p('service_reminder').days,
    difficulty: 'low',
    salesCopy: {
      promise: 'Servis zamanı gelen müşteri size döner, rakibe gitmez.',
      antiPatterns: [],
      checklist: ['Liste', 'Hatırlatma akışı'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['automotive'],
    upsellSlugs: ['eski-musteri-canlandirma'],
    legacyOfferIds: ['service_reminder'],
    legacyPlaybookNames: [],
  },
  {
    slug: 'veli-takip',
    familyId: 'sektor-akislari',
    name: 'Veli Takip Sistemi (Eğitim)',
    description: 'Veli adayı ile iletişim, bilgilendirme, deneme ders akışı.',
    defaultSetupPriceTl: p('parent_tracking').setup,
    defaultMonthlyPriceTl: p('parent_tracking').monthly,
    deliveryDays: p('parent_tracking').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Tüm veli iletişimi tek panelden, kaybolan soru kalmaz.',
      antiPatterns: [],
      checklist: ['Kanal birleştirme', 'Akış', 'Rapor'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['education'],
    upsellSlugs: ['kayit-pipeline'],
    legacyOfferIds: ['parent_tracking'],
    legacyPlaybookNames: [],
  },
  {
    slug: 'kayit-pipeline',
    familyId: 'sektor-akislari',
    name: 'Kayıt Pipeline (Eğitim)',
    description: 'Veli adayı → tanıtım → deneme → kayıt akışı.',
    defaultSetupPriceTl: p('enrollment_pipeline').setup,
    defaultMonthlyPriceTl: p('enrollment_pipeline').monthly,
    deliveryDays: p('enrollment_pipeline').days,
    difficulty: 'low',
    salesCopy: {
      promise: "Kayıt sezonu düzenli pipeline'a alınır, lead kaybolmaz.",
      antiPatterns: [],
      checklist: ['Stage tanımı', 'Otomatik geçiş', 'Rapor'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: ['education'],
    upsellSlugs: ['veli-takip'],
    legacyOfferIds: ['enrollment_pipeline'],
    legacyPlaybookNames: [],
  },
  {
    slug: 'rezervasyon-takip',
    familyId: 'sektor-akislari',
    name: 'Rezervasyon Takip (Turizm)',
    description: 'Rezervasyon hatırlatma, gelmeyen müşteri için yeniden teklif.',
    defaultSetupPriceTl: p('reservation_tracking').setup,
    defaultMonthlyPriceTl: p('reservation_tracking').monthly,
    deliveryDays: p('reservation_tracking').days,
    difficulty: 'low',
    salesCopy: {
      promise: 'Düşen rezervasyon telafi edilir, boş kontenjan azalır.',
      antiPatterns: [],
      checklist: ['Hatırlatma', 'Yeniden teklif akışı'],
    },
    requiredEvidenceKinds: ['places_data', 'review_signal'],
    targetSectors: ['tourism'],
    upsellSlugs: ['sadakat-sistemi', 'yorum-motoru'],
    legacyOfferIds: ['reservation_tracking'],
    legacyPlaybookNames: [],
  },

  // ══════════════════════ HİBRİT ══════════════════════
  {
    slug: 'ai-kreatif-lab',
    familyId: 'buyume-paketi',
    name: 'AI Kreatif & Reklam Test Laboratuvarı',
    description: 'Reklam kreatifi üretimi + A/B test + kazanan kreatif raporu + AI görsel üretimi.',
    defaultSetupPriceTl: p('ai_creative_lab').setup,
    defaultMonthlyPriceTl: p('ai_creative_lab').monthly,
    deliveryDays: p('ai_creative_lab').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Her ay düzenli kreatif üretimi, kazanan akışı testle netleşir.',
      antiPatterns: [],
      checklist: ['Kreatif briefi', 'Üretim sprintı', 'Test ve raporlama'],
    },
    requiredEvidenceKinds: ['html_signal', 'places_data'],
    targetSectors: ['ecommerce', 'real_estate'],
    upsellSlugs: ['reklam-optimizasyonu', 'satis-sonrasi-akislar'],
    legacyOfferIds: ['ai_creative_lab'],
    legacyPlaybookNames: ['AI Görsel Üretimi'],
  },
  {
    slug: 'reklam-optimizasyonu',
    familyId: 'buyume-paketi',
    name: 'Reklam Optimizasyonu',
    description: 'Meta/Google reklamlarında haftalık optimizasyon, hedefleme, bid yönetimi.',
    defaultSetupPriceTl: p('ads_optimization').setup,
    defaultMonthlyPriceTl: p('ads_optimization').monthly,
    deliveryDays: p('ads_optimization').days,
    difficulty: 'medium',
    salesCopy: {
      promise: 'Reklam hesabı düzenli optimize edilir; harcama görünür ve hesap verilebilir olur.',
      antiPatterns: [],
      checklist: ['Hesap audit', 'Optimizasyon sprintları', 'Aylık rapor'],
    },
    requiredEvidenceKinds: ['html_signal', 'places_data'],
    targetSectors: ['ecommerce', 'real_estate', 'automotive'],
    upsellSlugs: ['ai-kreatif-lab', 'dijital-reklam-gorselleri'],
    legacyOfferIds: ['ads_optimization'],
    legacyPlaybookNames: [],
  },
  {
    slug: 'guzellik-dijital-paketi',
    familyId: 'buyume-paketi',
    name: 'Güzellik Salonu Dijital Paketi',
    description: 'Tasarım + randevu otomasyonu + Google profili tek pakette (güzellik sektörü).',
    defaultSetupPriceTl: 5500,
    defaultMonthlyPriceTl: 3000,
    deliveryDays: 10,
    difficulty: 'low',
    salesCopy: {
      promise: 'Vitrin, randevu ve görünürlük tek pakette — salonunuz dijitalde tam takım.',
      antiPatterns: [],
      checklist: ['Profil + vitrin düzeni', 'Randevu akışı', 'Aylık görsel seti'],
    },
    requiredEvidenceKinds: ['places_data', 'html_signal'],
    targetSectors: ['beauty'],
    upsellSlugs: ['yorum-motoru', 'sosyal-medya-paketi'],
    legacyOfferIds: [],
    legacyPlaybookNames: ['Güzellik Salonu Dijital Paketi'],
  },
  {
    slug: 'kafe-restoran-dijital-paketi',
    familyId: 'buyume-paketi',
    name: 'Kafe & Restoran Dijital Paketi',
    description: 'Menü tasarımı + Google profili + yorum akışı tek pakette (yeme-içme).',
    defaultSetupPriceTl: 6000,
    defaultMonthlyPriceTl: 4000,
    deliveryDays: 10,
    difficulty: 'low',
    salesCopy: {
      promise: 'Menüden Google profiline tek elden dijital düzen — mekân dolulukla konuşur.',
      antiPatterns: [],
      checklist: ['Menü/görsel seti', 'Google profili', 'Yorum akışı'],
    },
    requiredEvidenceKinds: ['places_data', 'review_signal'],
    targetSectors: ['restaurant', 'tourism'],
    upsellSlugs: ['yorum-motoru', 'sosyal-medya-paketi'],
    legacyOfferIds: [],
    legacyPlaybookNames: ['Kafe & Restoran Dijital Paketi'],
  },
  {
    slug: 'google-isletme-profili',
    familyId: 'dijital-varlik',
    name: 'Google İşletme Profili & Yerel SEO',
    description: 'Google Maps profili optimizasyonu, fotoğraf yönetimi, yorum takibi, aylık güncelleme.',
    defaultSetupPriceTl: 2500,
    defaultMonthlyPriceTl: 3000,
    deliveryDays: 5,
    difficulty: 'low',
    salesCopy: {
      promise: "Google'da arandığınızda eksiksiz, güncel ve güven veren profil.",
      antiPatterns: [],
      checklist: ['Profil denetimi', 'Optimizasyon', 'Fotoğraf yükleme', 'Aylık güncelleme'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: [],
    upsellSlugs: ['yorum-motoru', 'web-sitesi'],
    legacyOfferIds: [],
    legacyPlaybookNames: ['SEO & Google İşletmem', 'Google Business Profil Yönetimi'],
  },
  {
    slug: 'rakip-analizi',
    familyId: 'dijital-varlik',
    name: 'Rakip Analizi Raporu',
    description: 'Sektördeki 5-10 rakibin dijital varlık, sosyal medya, fiyat ve konumlandırma analizi.',
    defaultSetupPriceTl: 3000,
    defaultMonthlyPriceTl: 0,
    deliveryDays: 7,
    difficulty: 'low',
    salesCopy: {
      promise: 'Rakiplerin ne yaptığı veriyle ortaya çıkar; boşluklar fırsata çevrilir.',
      antiPatterns: [],
      checklist: ['Rakip belirleme', 'Dijital varlık analizi', 'SWOT', 'Rapor sunumu'],
    },
    requiredEvidenceKinds: ['places_data'],
    targetSectors: [],
    upsellSlugs: ['web-sitesi', 'google-isletme-profili'],
    legacyOfferIds: [],
    legacyPlaybookNames: ['Rakip Analizi Raporu'],
  },
]

// ── Erişim yardımcıları ──────────────────────────────────────────────────────

const familyById = new Map(SERVICE_FAMILIES.map((f) => [f.id, f]))
const packageBySlug = new Map(SERVICE_PACKAGES.map((pkg) => [pkg.slug, pkg]))

export function findServiceBySlug(slug: string): ServicePackage | undefined {
  return packageBySlug.get(slug)
}

export function findFamilyById(id: string): ServiceFamily | undefined {
  return familyById.get(id)
}

export function domainOfPackage(pkg: ServicePackage): ServiceDomain {
  return familyById.get(pkg.familyId)?.domain ?? 'tasarim'
}

export function packagesByDomain(domain: ServiceDomain): ServicePackage[] {
  return SERVICE_PACKAGES.filter((pkg) => domainOfPackage(pkg) === domain)
}

// ── Compatibility adapter (SALT-OKUNUR) ─────────────────────────────────────
// Legacy offers.ts id'leri ve playbook adları → kanonik slug.
// offerMapping.resolveOfferId deseninin katalog karşılığı.

const legacyOfferMap = new Map<string, string>()
const legacyPlaybookMap = new Map<string, string>()
for (const pkg of SERVICE_PACKAGES) {
  for (const id of pkg.legacyOfferIds) legacyOfferMap.set(id, pkg.slug)
  for (const name of pkg.legacyPlaybookNames) legacyPlaybookMap.set(name.toLowerCase(), pkg.slug)
}

// Kanonik slug zaten verilmişse aynen döner; legacy offer id veya playbook adı
// ise kanonik slug'a çözer; tanınmıyorsa null (asla uydurma yok).
export function resolveServiceSlug(idOrName: string | null | undefined): string | null {
  if (!idOrName) return null
  const trimmed = idOrName.trim()
  if (packageBySlug.has(trimmed)) return trimmed
  const byOffer = legacyOfferMap.get(trimmed)
  if (byOffer) return byOffer
  return legacyPlaybookMap.get(trimmed.toLowerCase()) ?? null
}

// Testlerin tam kapsama iddiası için dışa açık sabitler.
export const LEGACY_OFFER_IDS_COVERED = [...legacyOfferMap.keys()]
export const LEGACY_PLAYBOOK_NAMES_COVERED = [...legacyPlaybookMap.keys()]
