-- =============================================================================
-- Feed The Goat / Yaşam OS — Life Supabase ŞEMA SNAPSHOT (001)
-- =============================================================================
-- Bu dosya, AgencyOS ana DB'sinden (supabase/migrations/, ref dfedeh…) AYRI olan
-- İKİNCİ Supabase projesinin (Life, ref xcqrk…) yeniden kurulabilir şemasıdır.
-- Hayat sayfaları (Günlük/Gelişim/Akademi/Kütüphane/Finans) + Asistan + Command
-- Center bu tabloları kullanır.
--
-- Kolonlar, koddaki gerçek .from()/.select()/.insert()/.upsert() kullanımından
-- türetildi (read-only mining). Mevcut prod tabloları farklıysa ALTER ile uyarla.
--
-- UYGULAMA: Bu dosya repo içinde KANIT amaçlıdır. Supabase SQL Editor'da MANUEL
-- uygula (otomatik migration YOK). idempotent: `create table if not exists`.
--
-- RLS: Aşağıda enable + servis/anon politikaları COMMENTED olarak verilmiştir.
-- App tek-operatör modeli (APP_PASSWORD kapısı) ile çalışır ve Life sayfaları
-- server-side anon client + service-role kullanır. RLS'i açmadan önce hangi
-- client'ın hangi tabloyu okuduğunu doğrula; yanlış politika app'i kilitleyebilir.
-- =============================================================================

-- ───────────────────────── Günlük (daily) ───────────────────────────────────

create table if not exists daily_v2 (
  date              date primary key,
  day_mode          text,
  agency_load       text,
  energy            text,
  protein_meal      boolean default false,
  water_3l          boolean default false,
  walk_35           boolean default false,
  english_done      boolean default false,
  ui_mode           text,
  max_auto_tasks    integer,
  locked_modules    jsonb default '[]'::jsonb,
  unlocked_modules  jsonb default '[]'::jsonb,
  assistant_reason  text,
  next_action       text,
  today_plan_json   jsonb,
  updated_at        timestamptz default now()
);

create table if not exists daily_quotes (
  id          bigint generated by default as identity primary key,
  date        date not null unique,
  quote       text not null,
  author      text
);

create table if not exists quote_pool (
  id          bigint generated by default as identity primary key,
  quote       text not null,
  author      text,
  used_on     date
);

create table if not exists daily_completions (
  id            bigint generated by default as identity primary key,
  template_id   bigint,
  date          date not null,
  created_at    timestamptz default now(),
  unique (template_id, date)
);

create table if not exists daily_scores (
  id                bigint generated by default as identity primary key,
  date              date not null unique,
  total_score       numeric,
  total_possible    numeric,
  completion_rate   numeric,
  finalized         boolean default false,
  created_at        timestamptz default now()
);

create table if not exists goat_state (
  id                   integer primary key default 1,
  last_finalized       date,
  current_streak       integer default 0,
  longest_streak       integer default 0,
  consistency_days     integer default 0,
  weekly_consistency   numeric,
  updated_at           timestamptz default now()
);

-- ───────────────────────── Alışkanlıklar (habits) ───────────────────────────

create table if not exists habits (
  id            bigint generated by default as identity primary key,
  key           text not null unique,
  is_active     boolean default true,
  target        numeric,
  cadence_type  text,
  sort_order    integer default 0
);

create table if not exists habit_logs (
  id          bigint generated by default as identity primary key,
  habit_key   text not null,
  date        date not null,
  value       integer default 0,
  unique (habit_key, date)
);

-- ───────────────────────── Finans (finance) ─────────────────────────────────

create table if not exists finance_state (
  id            integer primary key default 1,
  net_balance   numeric default 0
);

create table if not exists finance_transactions (
  id          bigint generated by default as identity primary key,
  type        text not null,                 -- income | expense
  title       text not null,
  amount      numeric not null,
  month       text,                          -- yyyy-MM
  category    text,
  priority    text,
  status      text,
  due_date    date,
  notes       text,
  created_at  timestamptz default now()
);
create index if not exists finance_transactions_month_idx on finance_transactions (month);
create index if not exists finance_transactions_type_idx on finance_transactions (type);

create table if not exists finance_fixed_expenses (
  id            bigint generated by default as identity primary key,
  title         text not null,
  amount        numeric not null,
  currency      text not null default 'TRY',
  category      text,
  day_of_month  integer,
  is_active     boolean default true,
  note          text,
  updated_at    timestamptz default now()
);

create table if not exists finance_subscriptions (
  id                bigint generated by default as identity primary key,
  title             text not null,
  amount            numeric not null,
  currency          text not null default 'TRY',
  is_active         boolean default true,
  category          text,
  billing_cycle     text,
  is_essential      boolean default false,
  revenue_impact    text,
  ai_recommendation text,
  purpose           text,
  renewal_day       integer,
  notes             text
);

-- ───────────────────────── Asistan (assistant) ──────────────────────────────

create table if not exists assistant_daily_state (
  id            bigint generated by default as identity primary key,
  date          date not null unique,
  energy        text,                          -- low | medium | high
  agency_load   text,                          -- low | normal | high
  mode          text                           -- koruma | denge | atak
);

create table if not exists assistant_knowledge (
  id          bigint generated by default as identity primary key,
  rel         text not null unique,            -- normalize edilmiş dosya yolu
  content     text
);

create table if not exists assistant_prefs (
  id              integer primary key default 1,
  food_likes      jsonb default '[]'::jsonb,
  food_dislikes   jsonb default '[]'::jsonb,
  notes           jsonb default '{}'::jsonb,
  updated_at      timestamptz default now()
);

create table if not exists assistant_reminders (
  id                    bigint generated by default as identity primary key,
  date                  date not null,
  reminder_type         text not null,         -- morning_checkin | midday_status | night_shutdown | evening_rhythm | deferred_task
  status                text default 'pending',-- pending | snoozed | sent
  scheduled_at          timestamptz,
  metadata              jsonb,
  sent_at               timestamptz,
  telegram_message_id   bigint,
  created_at            timestamptz default now(),
  updated_at            timestamptz default now(),
  unique (date, reminder_type)
);

-- ───────────────────────── Command Center ───────────────────────────────────

create table if not exists command_snapshots (
  id            bigint generated by default as identity primary key,
  app           text not null,                 -- agencyos | news-ai | xagent
  date          date not null,
  status        text,                          -- ok | stale | degraded | empty | down
  data          jsonb,
  warnings      jsonb default '[]'::jsonb,
  generated_at  timestamptz default now(),
  unique (app, date)
);

create table if not exists command_actions (
  id          bigint generated by default as identity primary key,
  date        date not null,
  action_key  text not null,                   -- agency_sales | news_read | xagent_approve
  state       text default 'pending',          -- pending | done | skipped
  updated_at  timestamptz default now(),
  unique (date, action_key)
);

create table if not exists command_plans (
  id          bigint generated by default as identity primary key,
  date        date not null unique,
  plan        jsonb,                            -- { lock, support[], minimumDay, actions, sourceHealth }
  updated_at  timestamptz default now()
);

-- ───────────────────────── Akademi (university) ─────────────────────────────

create table if not exists universities (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  name        text not null,
  created_at  timestamptz default now()
);

create table if not exists university_points (
  id          bigint generated by default as identity primary key,
  points      integer default 0,
  action      text,
  course_id   text,
  created_at  timestamptz default now()
);

-- ───────────────────────── Görevler (tasks) ─────────────────────────────────

create table if not exists active_tasks (
  id            bigint generated by default as identity primary key,
  title         text not null,
  is_done       boolean default false,
  category      text default 'active',         -- active | waiting
  sort_order    integer default 0,
  is_priority   boolean default false,
  note          text,
  description   text,
  due_date      date,
  created_at    timestamptz default now()
);

create table if not exists active_task_steps (
  id          bigint generated by default as identity primary key,
  task_id     bigint not null references active_tasks (id) on delete cascade,
  title       text not null,
  is_done     boolean default false,
  sort_order  integer default 0,
  created_at  timestamptz default now()
);

create table if not exists task_templates (
  id            bigint generated by default as identity primary key,
  title         text not null,
  section       text,                           -- rutin | kritik | x_post | sistem
  points        integer default 0,
  sort_order    integer default 0,
  system_type   text,                           -- vitamin | skincare | treadmill | english | x_post | saz | sport
  active_days   jsonb default '[]'::jsonb       -- gün anahtarları
);

-- =============================================================================
-- RLS (opsiyonel — uygulamadan ÖNCE gözden geçir)
-- =============================================================================
-- Life sayfaları server-side anon client + service-role kullanır. Aşağıdaki blok
-- her tabloda RLS açıp service_role'a tam, authenticated/anon'a okuma izni verir.
-- Tek-operatör app'inde anon-server okuması gerekiyorsa anon SELECT'i koru.
-- Doğrulanana kadar YORUMDA bırakıldı.
--
-- do $$
-- declare t text;
-- begin
--   foreach t in array array[
--     'daily_v2','daily_quotes','quote_pool','daily_completions','daily_scores',
--     'goat_state','habits','habit_logs','finance_state','finance_transactions',
--     'finance_fixed_expenses','finance_subscriptions','assistant_daily_state',
--     'assistant_knowledge','assistant_prefs','assistant_reminders',
--     'command_snapshots','command_actions','command_plans','universities',
--     'university_points','active_tasks','active_task_steps','task_templates'
--   ] loop
--     execute format('alter table %I enable row level security;', t);
--     execute format('create policy %I on %I for all to service_role using (true) with check (true);', t||'_svc', t);
--     execute format('create policy %I on %I for select to anon, authenticated using (true);', t||'_read', t);
--   end loop;
-- end $$;
