-- Migration 004 — /akademi tek üniversiteye (Beykent) sadeleştirme + Anadolu arşivi.
-- LIFE Supabase (ref xcqrk…). Manuel uygulanır (SQL Editor). Idempotent.
--
-- Ne yapar:
--   1) Taze Beykent AGNO tabloları (akademi_courses, akademi_exams) + RLS.
--   2) Eski 2-üniversiteli akademi sistemini ARŞİVLER (archived=true). HİÇBİR satır
--      DELETE edilmez — AÖF'ün 61 dersi/5 sınavı dahil tüm veri DB'de durur, tek
--      update ile geri gelir (bkz. 004_akademi_single_beykent_rollback.sql).
--   3) 14 ders + TMD intibak kalemi seed.
--   4) Eşleşen gelecek Beykent bütünlemelerini yeni tabloya kopyalar (hero countdown).

-- ───────────────────────── 1) Yeni tablolar ─────────────────────────────────
create table if not exists akademi_courses (
  id              bigint generated by default as identity primary key,
  name            text not null,
  term            text not null,                    -- 'guz' | 'bahar'
  akts            integer not null,
  kind            text not null,                    -- 'retake' | 'new' (AGNO paydası)
  category        text not null default 'zorunlu',  -- 'zorunlu' | 'secmeli'
  status          text not null default 'alinacak', -- alinacak | aktif | gecti | kaldi
  expected_letter text,                             -- AA..DZ | null (projeksiyon)
  actual_letter   text,                             -- AA..DZ | null (kesin sonuç)
  is_risk         boolean not null default false,   -- capstone/yüksek-AKTS glow
  in_average      boolean not null default true,    -- TMD intibak için false
  sort_order      integer not null default 0,
  created_at      timestamptz default now(),
  unique (name, term)
);

create table if not exists akademi_exams (
  id          bigint generated by default as identity primary key,
  course_id   bigint references akademi_courses (id) on delete set null,
  course_name text,                                 -- link yoksa fallback
  exam_type   text not null,                        -- 'vize' | 'final' | 'butunleme'
  exam_date   date not null,
  exam_time   text,                                 -- 'HH:MM' | null
  created_at  timestamptz default now()
);

-- RLS: proje pattern'i (002_life_rls) → RLS açık + policy yok = anon/authenticated
-- tam red; service-role baypas eder. Yeni tablolar 002'den sonra oluştuğundan burada
-- açıkça etkinleştirilir.
alter table akademi_courses enable row level security;
alter table akademi_exams   enable row level security;

-- ───────────────────────── 2) Eski sistemi arşivle ──────────────────────────
-- Idempotent + to_regclass guard (tablo yoksa no-op). Veri silinmez, sadece işaretlenir.
do $$
begin
  if to_regclass('public.universities') is not null then
    alter table universities add column if not exists archived boolean default false;
    update universities set archived = true where archived is distinct from true;
  end if;
  if to_regclass('public.courses') is not null then
    alter table courses add column if not exists archived boolean default false;
    update courses set archived = true where archived is distinct from true;
  end if;
  if to_regclass('public.exams') is not null then
    alter table exams add column if not exists archived boolean default false;
    update exams set archived = true where archived is distinct from true;
  end if;
  if to_regclass('public.university_points') is not null then
    alter table university_points add column if not exists archived boolean default false;
    update university_points set archived = true where archived is distinct from true;
  end if;
end $$;

-- ───────────────────────── 3) 14 ders + TMD seed ────────────────────────────
-- on conflict do nothing → kullanıcı düzenlemelerini (beklenen-not, durum) EZMEZ.
insert into akademi_courses (name, term, akts, kind, category, is_risk, in_average, sort_order) values
  ('Temel Tasarım',                                'guz',  6, 'retake', 'zorunlu', false, true,  1),
  ('Sosyal Bilimler İçin İstatistik',             'guz',  6, 'retake', 'zorunlu', false, true,  2),
  ('Görsel Kültür',                                'guz',  5, 'retake', 'zorunlu', false, true,  3),
  ('İletişim Sosyolojisi',                         'guz',  4, 'retake', 'zorunlu', false, true,  4),
  ('Hukukun Temelleri',                            'guz',  5, 'new',    'zorunlu', false, true,  5),
  ('Medya Tarihi',                                 'guz',  5, 'new',    'zorunlu', false, true,  6),
  ('SEC_7_3 (7. yarıyıl seçmeli)',                 'guz',  6, 'new',    'secmeli', false, true,  7),
  ('Görsel İlet. Tas. Bitirme Çalışması (Video)',  'bahar', 7, 'retake', 'zorunlu', true,  true,  8),
  ('İnteraktif Medya Tasarımı',                    'bahar', 6, 'retake', 'zorunlu', false, true,  9),
  ('İletişim Kuramları',                           'bahar', 5, 'retake', 'zorunlu', false, true, 10),
  ('İngilizce II',                                 'bahar', 4, 'retake', 'zorunlu', false, true, 11),
  ('Temel Tasarım Pratikleri',                     'bahar', 4, 'retake', 'zorunlu', false, true, 12),
  ('Dijital Oyun Tasarımı',                        'bahar', 5, 'retake', 'secmeli', false, true, 13),
  ('Kentsel Grafik',                               'bahar', 5, 'retake', 'zorunlu', false, true, 14),
  ('TMD I–V (İntibak)',                            'guz',  0, 'retake', 'zorunlu', false, false, 99)
on conflict (name, term) do nothing;

-- ───────────────────────── 4) Gelecek bütünlemeleri kopyala ─────────────────
-- Eski exams tablosundaki (arşivli) Temmuz bütünlemeleri canonical 14'le eşleşiyor.
-- Kaynak arşivde KALIR; burada yalnız kopya seed'lenir. Idempotent.
insert into akademi_exams (course_id, course_name, exam_type, exam_date)
select c.id, c.name, 'butunleme', d.dt
from (values
  ('İngilizce II',       '2026-07-08'::date),
  ('İletişim Kuramları', '2026-07-09'::date)
) as d(nm, dt)
join akademi_courses c on c.name = d.nm
where not exists (
  select 1 from akademi_exams e where e.course_name = d.nm and e.exam_date = d.dt
);
