-- Migration 007 (LIFE DB — xcqrk…) — GrafikcemOS köprüsü denetim kaydı.
--
-- ⚠️ MANUEL UYGULANIR. Repo şemanın kanıt/versiyon kaydıdır; otomatik migration YOK.
-- Bu dosya LIFE projesinde (xcqrk…) çalıştırılır — App DB'de (dfedeh…) DEĞİL.
--
-- NEDEN LIFE DB'DE: köprünün yazma yolu LIFE tablolarına (active_tasks,
-- habit_logs, …) dokunuyor. Idempotency anahtarının UNIQUE olduğu tablo, yazmanın
-- gerçekleştiği veritabanıyla AYNI olmalı; ayrı DB'de tutulsaydı iki eşzamanlı
-- istek arasında "denetim yazıldı ama görev yazılamadı" (veya tersi) durumu
-- oluşabilirdi ve tekrar-oynatma koruması sessizce delinirdi.
--
-- NE SAKLANMAZ: token, ham gövde, görev/alışkanlık metni, kişisel içerik.
-- Yalnız yolun adı, kapalı küme durum, gövdenin sha256'sı ve sayaç özeti.
--
-- Idempotent: yeniden çalıştırmak güvenlidir.

BEGIN;

CREATE TABLE IF NOT EXISTS public.cemos_bridge_audit (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts                timestamptz NOT NULL DEFAULT now(),
  route             text NOT NULL,
  method            text NOT NULL,
  scope             text NOT NULL CHECK (scope IN ('read', 'write')),
  -- Okuma isteklerinde NULL; yazmalarda ZORUNLU ve BENZERSIZ.
  idempotency_key   text,
  request_hash      text,
  status            integer NOT NULL,
  response_summary  jsonb,
  error             text
);

-- Kısmi UNIQUE: NULL anahtarlar (okumalar) çakışmaz, yazma anahtarı tektir.
CREATE UNIQUE INDEX IF NOT EXISTS uq_cemos_bridge_idem
  ON public.cemos_bridge_audit (idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cemos_bridge_ts
  ON public.cemos_bridge_audit (ts DESC);

-- RLS: açık + SIFIR policy. service_role baypas eder; anon/authenticated tam red.
ALTER TABLE public.cemos_bridge_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.cemos_bridge_audit FROM anon, authenticated;

COMMIT;

NOTIFY pgrst, 'reload schema';
